/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/mixabotsplit.glb')
  const { actions } = useAnimations(animations, group)

  console.dir(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Alpha_Joints.geometry}
          material={materials.Alpha_Joints_MAT}
          skeleton={nodes.Alpha_Joints.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface.geometry}
          material={nodes.Alpha_Surface.material}
          skeleton={nodes.Alpha_Surface.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface001.geometry}
          material={nodes.Alpha_Surface001.material}
          skeleton={nodes.Alpha_Surface001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface002.geometry}
          material={nodes.Alpha_Surface002.material}
          skeleton={nodes.Alpha_Surface002.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface003.geometry}
          material={nodes.Alpha_Surface003.material}
          skeleton={nodes.Alpha_Surface003.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface004.geometry}
          material={nodes.Alpha_Surface004.material}
          skeleton={nodes.Alpha_Surface004.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface005.geometry}
          material={nodes.Alpha_Surface005.material}
          skeleton={nodes.Alpha_Surface005.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface006.geometry}
          material={nodes.Alpha_Surface006.material}
          skeleton={nodes.Alpha_Surface006.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface007.geometry}
          material={nodes.Alpha_Surface007.material}
          skeleton={nodes.Alpha_Surface007.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface008.geometry}
          material={nodes.Alpha_Surface008.material}
          skeleton={nodes.Alpha_Surface008.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface009.geometry}
          material={nodes.Alpha_Surface009.material}
          skeleton={nodes.Alpha_Surface009.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface010.geometry}
          material={nodes.Alpha_Surface010.material}
          skeleton={nodes.Alpha_Surface010.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface011.geometry}
          material={nodes.Alpha_Surface011.material}
          skeleton={nodes.Alpha_Surface011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface012.geometry}
          material={nodes.Alpha_Surface012.material}
          skeleton={nodes.Alpha_Surface012.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface013.geometry}
          material={nodes.Alpha_Surface013.material}
          skeleton={nodes.Alpha_Surface013.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface014.geometry}
          material={nodes.Alpha_Surface014.material}
          skeleton={nodes.Alpha_Surface014.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface015.geometry}
          material={nodes.Alpha_Surface015.material}
          skeleton={nodes.Alpha_Surface015.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface016.geometry}
          material={nodes.Alpha_Surface016.material}
          skeleton={nodes.Alpha_Surface016.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface017.geometry}
          material={nodes.Alpha_Surface017.material}
          skeleton={nodes.Alpha_Surface017.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface018.geometry}
          material={nodes.Alpha_Surface018.material}
          skeleton={nodes.Alpha_Surface018.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface019.geometry}
          material={nodes.Alpha_Surface019.material}
          skeleton={nodes.Alpha_Surface019.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface020.geometry}
          material={nodes.Alpha_Surface020.material}
          skeleton={nodes.Alpha_Surface020.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface021.geometry}
          material={nodes.Alpha_Surface021.material}
          skeleton={nodes.Alpha_Surface021.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface022.geometry}
          material={nodes.Alpha_Surface022.material}
          skeleton={nodes.Alpha_Surface022.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface023.geometry}
          material={nodes.Alpha_Surface023.material}
          skeleton={nodes.Alpha_Surface023.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface024.geometry}
          material={nodes.Alpha_Surface024.material}
          skeleton={nodes.Alpha_Surface024.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface025.geometry}
          material={nodes.Alpha_Surface025.material}
          skeleton={nodes.Alpha_Surface025.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface026.geometry}
          material={nodes.Alpha_Surface026.material}
          skeleton={nodes.Alpha_Surface026.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface027.geometry}
          material={nodes.Alpha_Surface027.material}
          skeleton={nodes.Alpha_Surface027.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface028.geometry}
          material={nodes.Alpha_Surface028.material}
          skeleton={nodes.Alpha_Surface028.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface029.geometry}
          material={nodes.Alpha_Surface029.material}
          skeleton={nodes.Alpha_Surface029.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface030.geometry}
          material={nodes.Alpha_Surface030.material}
          skeleton={nodes.Alpha_Surface030.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface031.geometry}
          material={nodes.Alpha_Surface031.material}
          skeleton={nodes.Alpha_Surface031.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface032.geometry}
          material={nodes.Alpha_Surface032.material}
          skeleton={nodes.Alpha_Surface032.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface033.geometry}
          material={nodes.Alpha_Surface033.material}
          skeleton={nodes.Alpha_Surface033.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface034.geometry}
          material={nodes.Alpha_Surface034.material}
          skeleton={nodes.Alpha_Surface034.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface035.geometry}
          material={nodes.Alpha_Surface035.material}
          skeleton={nodes.Alpha_Surface035.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface036.geometry}
          material={nodes.Alpha_Surface036.material}
          skeleton={nodes.Alpha_Surface036.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface037.geometry}
          material={nodes.Alpha_Surface037.material}
          skeleton={nodes.Alpha_Surface037.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface038.geometry}
          material={nodes.Alpha_Surface038.material}
          skeleton={nodes.Alpha_Surface038.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface039.geometry}
          material={nodes.Alpha_Surface039.material}
          skeleton={nodes.Alpha_Surface039.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface040.geometry}
          material={nodes.Alpha_Surface040.material}
          skeleton={nodes.Alpha_Surface040.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface041.geometry}
          material={nodes.Alpha_Surface041.material}
          skeleton={nodes.Alpha_Surface041.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface042.geometry}
          material={nodes.Alpha_Surface042.material}
          skeleton={nodes.Alpha_Surface042.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface043.geometry}
          material={nodes.Alpha_Surface043.material}
          skeleton={nodes.Alpha_Surface043.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface044.geometry}
          material={nodes.Alpha_Surface044.material}
          skeleton={nodes.Alpha_Surface044.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface045.geometry}
          material={nodes.Alpha_Surface045.material}
          skeleton={nodes.Alpha_Surface045.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface046.geometry}
          material={nodes.Alpha_Surface046.material}
          skeleton={nodes.Alpha_Surface046.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Alpha_Surface047.geometry}
          material={nodes.Alpha_Surface047.material}
          skeleton={nodes.Alpha_Surface047.skeleton}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[0, 0.14, -94.92]} rotation={[-1.59, -0.02, -0.02]}>
          <group position={[0, 10.68, -0.87]} rotation={[-0.06, 0, -0.03]}>
            <group position={[0, 12.5, 0]} rotation={[-0.07, 0, 0]}>
              <group position={[0, 14.29, 0]} rotation={[-0.07, 0, 0]}>
                <group position={[0, 16.08, 0]} rotation={[0.03, -0.01, -0.01]}>
                  <group position={[0, 7.7, 2.69]} rotation={[-0.14, -0.09, -0.17]} />
                </group>
                <group position={[6.42, 14.32, -0.14]} rotation={[1.56, -0.59, -1.7]}>
                  <group position={[0, 13.45, 0]} rotation={[0.76, 0.37, -0.1]}>
                    <group position={[0, 28.43, 0]} rotation={[0.01, 0, 0.15]} scale={[1, 1, 1]}>
                      <group position={[0, 21.75, 0]} rotation={[0.06, 0.04, -0.07]}>
                        <group position={[-2.97, 3.03, 1.29]} rotation={[-0.01, 0.15, 0.48]}>
                          <group position={[-0.6, 3.5, 0]} rotation={[0.31, 0, -0.13]} scale={[1, 1, 1]}>
                            <group position={[0.08, 3.37, 0]} rotation={[-0.42, -0.11, 0.42]} scale={[1, 1, 1]} />
                          </group>
                        </group>
                        <group position={[-3.48, 9.6, 0.26]} rotation={[0.31, 0.01, 0.15]} scale={[1, 1, 1]}>
                          <group position={[0.04, 3.41, 0]} rotation={[0.56, -0.03, -0.09]} scale={[1, 1, 1]}>
                            <group position={[-0.01, 3.15, 0]} rotation={[0.33, -0.01, -0.06]} />
                          </group>
                        </group>
                        <group position={[-1.07, 10.21, -0.3]} rotation={[0.32, 0.01, 0.03]}>
                          <group position={[0.02, 3.51, 0]} rotation={[0.52, -0.02, -0.08]}>
                            <group position={[-0.02, 3.27, 0]} rotation={[0.44, -0.01, -0.06]} />
                          </group>
                        </group>
                        <group position={[1.22, 10.37, -0.34]} rotation={[0.45, 0, -0.06]}>
                          <group position={[-0.01, 2.91, 0]} rotation={[0.59, -0.02, -0.08]}>
                            <group position={[0, 2.72, 0]} rotation={[0.62, -0.03, -0.09]} />
                          </group>
                        </group>
                        <group position={[3.33, 9.21, 0.03]} rotation={[0.48, -0.15, -0.02]}>
                          <group position={[0.01, 2.65, 0]} rotation={[0.57, -0.03, -0.09]}>
                            <group position={[-0.01, 2.3, 0]} rotation={[0.47, -0.01, -0.06]} scale={[1, 1, 1]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-6.42, 14.32, -0.14]} rotation={[1.56, 0.49, 1.7]}>
                  <group position={[0, 13.45, 0]} rotation={[0.92, 0.08, 0.17]} scale={[1, 1, 1]}>
                    <group position={[0, 28.42, 0]} rotation={[0.02, 0, -0.25]} scale={[1, 1, 1]}>
                      <group position={[0, 21.74, 0]} rotation={[0.01, -0.27, -0.15]}>
                        <group position={[3.01, 3.19, 1.38]} rotation={[0.13, -0.18, -0.45]} scale={[1, 1, 1]}>
                          <group position={[0.66, 3.62, 0]} rotation={[0.18, -0.07, 0.14]}>
                            <group position={[-0.11, 3.29, 0]} rotation={[-0.35, 0.13, -0.48]} />
                          </group>
                        </group>
                        <group position={[3.62, 9.94, 0.13]} rotation={[0.19, -0.01, -0.19]}>
                          <group position={[-0.01, 3.3, 0]} rotation={[0.69, 0.02, 0.07]}>
                            <group position={[0.01, 3.01, 0]} rotation={[0.48, 0.01, 0.04]} />
                          </group>
                        </group>
                        <group position={[0.97, 10, -0.21]} rotation={[0.41, -0.01, -0.11]}>
                          <group position={[-0.02, 3.54, 0]} rotation={[0.61, 0.02, 0.06]} scale={[1, 1, 1]}>
                            <group position={[0.02, 3.37, 0]} rotation={[0.49, 0.01, 0.04]} />
                          </group>
                        </group>
                        <group position={[-1.17, 10.15, -0.22]} rotation={[0.53, 0, -0.01]} scale={[1, 1, 1]}>
                          <group position={[0, 2.91, 0]} rotation={[0.63, 0.02, 0.07]} scale={[1, 1, 1]}>
                            <group position={[0, 2.78, 0]} rotation={[0.41, 0.01, 0.04]} scale={[1, 1, 1]} />
                          </group>
                        </group>
                        <group position={[-3.42, 9.06, 0.04]} rotation={[0.48, 0.25, 0.09]}>
                          <group position={[-0.01, 2.73, 0]} rotation={[0.52, 0.02, 0.06]}>
                            <group position={[0.01, 2.31, 0]} rotation={[0.42, 0.01, 0.04]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[9.55, -5.93, -0.28]} rotation={[-0.06, 0.13, -3.06]} scale={[1, 1, 1]}>
            <group position={[0, 40.86, 0]} rotation={[-0.3, -0.04, 0.02]}>
              <group position={[0, 37.85, 0]} rotation={[1.25, -0.09, 0.06]} scale={[1, 1, 1]}>
                <group position={[0, 17.38, 0]} rotation={[0.59, -0.1, 0.07]} />
              </group>
            </group>
          </group>
          <group position={[-9.55, -5.93, -0.43]} rotation={[0.03, -0.19, 3.05]}>
            <group position={[0, 40.81, 0]} rotation={[-0.16, 0.12, -0.01]}>
              <group position={[0, 37.85, 0]} rotation={[1.17, 0.11, -0.04]}>
                <group position={[0, 17.9, 0]} rotation={[0.58, 0.11, -0.07]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mixabotsplit.glb')
