/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/groundconcreete.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-2.92, 0.01, 0.9]} rotation={[-0.27, 0.6, 1.93]} scale={[1, 1, 1]} />
        <group position={[-3, -1, 0]}>
          <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
        </group>
        <group position={[-1, -1, 0]}>
          <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} />
        </group>
        <group position={[1, -1, 0]}>
          <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} />
        </group>
        <group position={[3, -1, 0]}>
          <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} />
        </group>
        <group position={[3, 1, 0]}>
          <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} />
        </group>
        <group position={[1, 1, 0]}>
          <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} />
        </group>
        <group position={[-1, 1, 0]}>
          <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} />
        </group>
        <group position={[-3, 1, 0]}>
          <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/groundconcreete.glb')
