/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/helmety2.glb')
 console.dir(materials.Ch20_body)

  const { actions } = useAnimations(animations, group)
 
  useEffect(() => { 
    actions.capoo.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorig6Hips} />
        <skinnedMesh castShadow geometry={nodes.Ch20.geometry} material={materials.Ch20_body} skeleton={nodes.Ch20.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/helmety2.glb')
