/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/livingroomtedmedia.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[8.92, 2.98, -5.06]}>
        <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
        <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        <group position={[-5.5, -1.94, -3.22]}>
          <mesh
            geometry={nodes.Bread_1.geometry}
            material={nodes.Bread_1.material}
            position={[-0.02, -0.01, 0.02]}
            rotation={[0, 0, 0.01]}
            scale={[12.43, 12.43, 12.43]}
          />
          <mesh
            geometry={nodes.Bread_2001.geometry}
            material={nodes.Bread_2001.material}
            position={[0.02, 0.01, -0.02]}
            rotation={[3.14, 0, 3.13]}
            scale={[12.43, 12.43, 12.43]}
          />
        </group>
        <group position={[-2.96, -1.46, -3.82]}>
          <mesh
            geometry={nodes.candle_2.geometry}
            material={nodes.candle_2.material}
            position={[0.05, 0.06, 0]}
            rotation={[0, 1.49, -Math.PI]}
            scale={[-0.88, -0.88, -0.88]}
          />
          <mesh
            geometry={nodes.candle_3.geometry}
            material={nodes.candle_3.material}
            position={[-0.04, 0.02, 0]}
            rotation={[0, 0.6, -Math.PI]}
            scale={[-0.88, -0.88, -0.88]}
          />
        </group>
        <group position={[-1.59, -0.82, 0.65]}>
          <mesh
            geometry={nodes.hours.geometry}
            material={nodes.hours.material}
            position={[0.01, -0.05, -0.04]}
            rotation={[0, 0, -0.61]}
            scale={[0.93, 0.93, 0.93]}
          />
          <mesh
            geometry={nodes.minutes.geometry}
            material={nodes.minutes.material}
            position={[0.01, -0.05, -0.03]}
            rotation={[0, 0, Math.PI / 4]}
            scale={[0.93, 0.93, 0.93]}
          />
          <mesh
            geometry={nodes.numbers.geometry}
            material={nodes.numbers.material}
            position={[0.01, 0.42, 0.03]}
            scale={[0.93, 0.93, 0.93]}
          />
        </group>
        <group position={[-9.27, -2.98, -0.32]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            geometry={nodes.door_frame002.geometry}
            material={nodes.door_frame002.material}
            position={[0, 1.28, 0.1]}
            scale={[0.31, 0.31, 0.22]}
          />
          <group position={[0.5, 0.28, -0.04]} rotation={[0, 0, 0]} scale={[0.12, 0.12, 0.12]}>
            <mesh geometry={nodes.door_1.geometry} material={nodes.door_1.material} />
            <mesh geometry={nodes.door_2.geometry} material={nodes.door_2.material} />
            <mesh geometry={nodes.door_3.geometry} material={nodes.door_3.material} />
            <mesh
              geometry={nodes.handle001.geometry}
              material={nodes.handle001.material}
              position={[-7.13, 7.92, 0.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.8, 0.8, 0.8]}
            />
          </group>
        </group>
        <group position={[-5.11, -2.98, 0.72]}>
          <mesh
            geometry={nodes.door_frame001.geometry}
            material={nodes.door_frame001.material}
            position={[0, 1.28, 0.1]}
            scale={[0.31, 0.31, 0.22]}
          />
          <group position={[0.5, 0.28, -0.04]} rotation={[0, 0, 0]} scale={[0.12, 0.12, 0.12]}>
            <mesh geometry={nodes.door_1.geometry} material={nodes.door_1.material} />
            <mesh geometry={nodes.door_2.geometry} material={nodes.door_2.material} />
            <mesh geometry={nodes.door_3.geometry} material={nodes.door_3.material} />
            <mesh
              geometry={nodes.handle.geometry}
              material={nodes.handle.material}
              position={[-7.13, 7.92, 0.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.8, 0.8, 0.8]}
            />
          </group>
        </group>
        <group position={[-8.16, -2.04, -3.89]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            geometry={nodes.Sink001.geometry}
            material={nodes.Sink001.material}
            position={[0.05, -0.04, 0.03]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.04, 0.04, 0.04]}
          />
          <mesh
            geometry={nodes.Tap.geometry}
            material={nodes.Tap.material}
            position={[-0.06, 0.1, -0.03]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[1.04, 1.04, 1.04]}
          />
        </group>
        <group position={[-1.53, -1.98, -3.74]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Screen.geometry} material={materials.screen} scale={[5.1, 5.17, 5.1]} />
          <mesh geometry={nodes.tv.geometry} material={materials.tv} scale={[5.1, 5.17, 5.1]} />
        </group>
        <group position={[-4.35, 0, -3.43]}>
          <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
          <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        </group>
        <group position={[-2.04, 0, -3.43]}>
          <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
          <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        </group>
        <group position={[0, 0, -3.43]}>
          <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
          <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        </group>
        <group position={[-4.35, 0, 0]}>
          <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
          <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        </group>
        <group position={[-2.04, 0, 0]}>
          <mesh geometry={nodes.LRaalll_1.geometry} material={nodes.LRaalll_1.material} />
          <mesh geometry={nodes.LRaalll_2.geometry} material={nodes.LRaalll_2.material} />
        </group>
        <group position={[2.38, -2.76, -4.11]}>
          <mesh geometry={nodes.Ball_1.geometry} material={materials['white plastic']} />
          <mesh geometry={nodes.Ball_2.geometry} material={materials['black plastic']} />
        </group>
        <mesh geometry={nodes.Basket.geometry} material={materials.Rattan} position={[-0.09, -2.71, 0.4]} />
        <mesh
          geometry={nodes.Beer.geometry}
          material={nodes.Beer.material}
          position={[2.65, -2.49, -1.07]}
          rotation={[-Math.PI, 0.33, -Math.PI]}
        />
        <mesh
          geometry={nodes['Beer_(1)'].geometry}
          material={nodes['Beer_(1)'].material}
          position={[2.97, -2.49, -1.53]}
          rotation={[0, 0.72, 0]}
        />
        <mesh
          geometry={nodes.Books_1.geometry}
          material={nodes.Books_1.material}
          position={[-3.61, -1.77, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Books_2.geometry}
          material={nodes.Books_2.material}
          position={[-3.62, -1.29, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Books_3.geometry}
          material={nodes.Books_3.material}
          position={[-3.56, -2.27, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Books_4.geometry}
          material={nodes.Books_4.material}
          position={[-3.51, -2.75, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Bottle_1.geometry}
          material={materials['bottle glass 1']}
          position={[-4.04, -0.77, -3.85]}
        />
        <mesh
          geometry={nodes.Bread.geometry}
          material={materials.bread}
          position={[-5.71, -1.89, -3]}
          rotation={[0, -0.89, 0]}
        />
        <group position={[-1.49, -2.67, -3.78]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Cabinet_1.geometry} material={materials['wood 2']} />
          <mesh geometry={nodes.Cabinet_2.geometry} material={materials['cabinet glass']} />
        </group>
        <group position={[-0.73, -2.34, -3.63]}>
          <mesh geometry={nodes.Candle_1.geometry} material={nodes.Candle_1.material} />
          <mesh geometry={nodes.Candle_3.geometry} material={nodes.Candle_3.material} />
        </group>
        <mesh geometry={nodes.Candle_2.geometry} material={nodes.Candle_2.material} position={[1.3, -2.85, -4.93]} />
        <mesh
          geometry={nodes['Candle_2_(1)'].geometry}
          material={nodes['Candle_2_(1)'].material}
          position={[3.14, -2.85, -8.6]}
        />
        <mesh
          geometry={nodes['Candle_2_(2)'].geometry}
          material={nodes['Candle_2_(2)'].material}
          position={[1.28, -2.85, 0.55]}
        />
        <mesh geometry={nodes.Carpet.geometry} material={materials.carpet} position={[-1.72, -2.97, -1.94]} />
        <mesh geometry={nodes.Ceiling.geometry} material={materials.Ceiling} position={[-4.16, 0.07, -1.71]} />
        <group position={[-7.41, -0.03, -1.74]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Ceiling_lamp_1.geometry} material={materials['lamp material']} />
          <mesh geometry={nodes.Ceiling_lamp_2.geometry} material={materials['lamp light 2']} />
        </group>
        <group position={[-6.65, -2.49, 0.26]}>
          <mesh geometry={nodes.Chair_1_1.geometry} material={materials['wood 1']} />
          <mesh geometry={nodes.Chair_1_2.geometry} material={materials.fabric1} />
        </group>
        <group position={[-4.86, -2.54, -2.23]} rotation={[0, 0.26, 0]}>
          <mesh geometry={nodes.Chair_2_1.geometry} material={nodes.Chair_2_1.material} />
          <mesh geometry={nodes.Chair_2_2.geometry} material={nodes.Chair_2_2.material} />
        </group>
        <group position={[-4.96, -2.54, -3.13]}>
          <mesh geometry={nodes.Chair_2_1.geometry} material={nodes.Chair_2_1.material} />
          <mesh geometry={nodes.Chair_2_2.geometry} material={nodes.Chair_2_2.material} />
        </group>
        <mesh geometry={nodes.Coffee.geometry} material={materials.coffee} position={[-1.18, -2.39, -1.38]} />
        <group position={[2.95, -2.34, -2.94]} rotation={[-Math.PI, 0.01, -Math.PI]}>
          <mesh geometry={nodes.Couch_1.geometry} material={nodes.Couch_1.material} />
          <mesh geometry={nodes.Couch_3.geometry} material={nodes.Couch_3.material} />
        </group>
        <group position={[2.95, -2.44, 0.49]}>
          <mesh geometry={nodes.Couch_2_1.geometry} material={nodes.Couch_2_1.material} />
          <mesh geometry={nodes.Couch_2_2.geometry} material={nodes.Couch_2_2.material} />
        </group>
        <group position={[4.89, -2.44, -1.37]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Couch_2_1.geometry} material={nodes.Couch_2_1.material} />
          <mesh geometry={nodes.Couch_2_2.geometry} material={nodes.Couch_2_2.material} />
        </group>
        <mesh
          geometry={nodes.Crystal_ball.geometry}
          material={materials['crystal ball']}
          position={[-2.95, -1.88, -3.81]}
        />
        <mesh
          geometry={nodes.Cup.geometry}
          material={materials.cup}
          position={[-1.62, -2.36, -1.5]}
          rotation={[0, 0.97, 0]}
        />
        <mesh geometry={nodes.Dice.geometry} material={materials.dice} position={[-3.06, -0.87, -3.87]} />
        <mesh geometry={nodes.Dish.geometry} material={materials.dish} position={[-8.85, -2.04, -3.75]} />
        <mesh
          geometry={nodes.Door_2.geometry}
          material={materials['Default-Material']}
          position={[0.75, -1.48, -1.72]}
          rotation={[0, Math.PI / 2, 0]}>
          <group position={[-0.89, -0.17, 0.05]} scale={[2.54, 2.54, 2.54]}>
            <mesh geometry={nodes.Door_1_1.geometry} material={nodes.Door_1_1.material} />
            <mesh geometry={nodes.Door_1_2.geometry} material={nodes.Door_1_2.material} />
          </group>
          <group position={[0.96, -0.17, 0]} scale={[2.54, 2.54, 2.54]}>
            <mesh geometry={nodes.Door_2001_1.geometry} material={nodes.Door_2001_1.material} />
            <mesh geometry={nodes.Door_2001_2.geometry} material={nodes.Door_2001_2.material} />
          </group>
          <mesh
            geometry={nodes.door_frame.geometry}
            material={nodes.door_frame.material}
            position={[0, -0.14, 0.07]}
            scale={[2.54, 2.54, 2.54]}
          />
        </mesh>
        <mesh
          geometry={nodes.Dvd.geometry}
          material={materials.dvd}
          position={[-1.05, -2.62, -3.62]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.Exhaust_hood.geometry}
          material={materials['Exhaust hood']}
          position={[-8.93, -0.77, -2.58]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group position={[2.91, -2.79, -1.3]}>
          <mesh geometry={nodes.Exterior_Table_1.geometry} material={nodes.Exterior_Table_1.material} />
          <mesh geometry={nodes.Exterior_Table_2.geometry} material={materials['glass 1']} />
        </group>
        <group position={[3.18, -1.77, -3.87]} rotation={[0, -Math.PI / 2, 0]} scale={[0.98, 0.98, 0.98]}>
          <mesh geometry={nodes.Exterior_Walls_1.geometry} material={materials['stone wall']} />
          <mesh geometry={nodes.Exterior_Walls_2.geometry} material={materials.Concrete} />
        </group>
        <mesh geometry={nodes.Floor.geometry} material={materials.floor} position={[-4.26, -3.01, -1.72]} />
        <mesh geometry={nodes.Fresh_cola.geometry} material={materials['can drink']} position={[2.62, -2.52, -1.48]} />
        <group position={[-7.09, -1.85, -3.75]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Fridge_1.geometry} material={materials.fridge} />
          <mesh geometry={nodes.Fridge_2.geometry} material={materials['fridge plastic']} />
        </group>
        <mesh
          geometry={nodes.Hotplate.geometry}
          material={materials.hotplate}
          position={[-8.89, -2.05, -2.57]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group position={[-8.63, -2.49, -3.02]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Kitchen_furniture_1_1.geometry} material={nodes.Kitchen_furniture_1_1.material} />
          <mesh geometry={nodes.Kitchen_furniture_1_2.geometry} material={materials['kitchen metallic']} />
          <mesh geometry={nodes.Kitchen_furniture_1_3.geometry} material={nodes.Kitchen_furniture_1_3.material} />
        </group>
        <group position={[-5.68, -2.47, -2.85]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Kitchen_furniture_2_1.geometry} material={nodes.Kitchen_furniture_2_1.material} />
          <mesh geometry={nodes.Kitchen_furniture_2_2.geometry} material={nodes.Kitchen_furniture_2_2.material} />
        </group>
        <group position={[-3.48, -1.91, 0.15]} rotation={[0, -1.12, 0]}>
          <mesh geometry={nodes.Lamp_1.geometry} material={materials['color lamp']} />
          <mesh geometry={nodes.Lamp_3.geometry} material={materials['lamp light']} />
        </group>
        <group position={[1.31, -2.55, -4.94]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Lamp_2_1.geometry} material={nodes.Lamp_2_1.material} />
          <mesh geometry={nodes.Lamp_2_2.geometry} material={nodes.Lamp_2_2.material} />
        </group>
        <group position={[3.14, -2.55, -8.59]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Lamp_2_1.geometry} material={nodes.Lamp_2_1.material} />
          <mesh geometry={nodes.Lamp_2_2.geometry} material={nodes.Lamp_2_2.material} />
        </group>
        <group position={[1.28, -2.55, 0.55]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Lamp_2_1.geometry} material={nodes.Lamp_2_1.material} />
          <mesh geometry={nodes.Lamp_2_2.geometry} material={nodes.Lamp_2_2.material} />
        </group>
        <mesh
          geometry={nodes.Microwave.geometry}
          material={materials.Microwave}
          position={[-8.94, -1.88, -1.81]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh geometry={nodes.Picture_1.geometry} material={materials['picture 1']} position={[-0.02, -1.02, 0.66]} />
        <mesh geometry={nodes.Pillow_1.geometry} material={materials['pillow 1']} position={[-1, -2.13, 0.28]} />
        <mesh
          geometry={nodes.Pillow_2.geometry}
          material={materials['pillow 2']}
          position={[-2.16, -2.14, 0.21]}
          rotation={[0, -0.48, 0]}
        />
        <mesh
          geometry={nodes.Pillow_3.geometry}
          material={materials['pillow 3']}
          position={[-1.4, -2.18, 0.11]}
          rotation={[0, 0.33, 0]}
        />
        <mesh geometry={nodes.Plant_1.geometry} material={materials.plant} position={[0.02, -2.53, -3.66]} />
        <group position={[1.42, -1.55, -7.99]}>
          <mesh geometry={nodes.Plant_3_1.geometry} material={nodes.Plant_3_1.material} />
          <mesh geometry={nodes.Plant_3_2.geometry} material={nodes.Plant_3_2.material} />
        </group>
        <group position={[5.04, -1.56, -7.99]}>
          <mesh geometry={nodes.Plant_3_1.geometry} material={nodes.Plant_3_1.material} />
          <mesh geometry={nodes.Plant_3_2.geometry} material={nodes.Plant_3_2.material} />
        </group>
        <group position={[-3.54, -1.98, -3.87]}>
          <mesh geometry={nodes.Shelving_1.geometry} material={materials['metallic 1']} />
          <mesh geometry={nodes.Shelving_2.geometry} material={materials['wood 3']} />
        </group>
        <group position={[-1.54, -2.49, 0.07]}>
          <mesh geometry={nodes.Sofa_1.geometry} material={materials.fabric2} />
          <mesh geometry={nodes.Sofa_2.geometry} material={materials.metallic} />
        </group>
        <mesh
          geometry={nodes.Switch.geometry}
          material={materials.Switch}
          position={[-9.23, -1.61, -1.15]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh geometry={nodes.Tea_table.geometry} material={materials['table 1']} position={[-1.5, -2.7, -1.6]} />
        <mesh
          geometry={nodes.Tv_remote.geometry}
          material={materials.buttons}
          position={[-1.02, -2.42, -1.55]}
          rotation={[0, 0.42, 0]}
        />
        <mesh
          geometry={nodes.Utensils.geometry}
          material={materials['metallic utensils_']}
          position={[-9.19, -1.59, -3.36]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh geometry={nodes.Wall_1.geometry} material={nodes.Wall_1.material} position={[-4.24, -1.48, 0.73]} />
        <mesh
          geometry={nodes.Wall_2.geometry}
          material={nodes.Wall_2.material}
          position={[-9.27, -1.48, -1.73]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh geometry={nodes.Wall_3.geometry} material={nodes.Wall_3.material} position={[-4.27, -1.48, -4.22]} />
        <mesh
          geometry={nodes.Wall_4.geometry}
          material={nodes.Wall_4.material}
          position={[0.75, -1.48, -1.73]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group position={[-7.36, -1.48, 0.75]}>
          <mesh geometry={nodes.Window_1.geometry} material={nodes.Window_1.material} />
          <mesh geometry={nodes.Window_2.geometry} material={nodes.Window_2.material} />
        </group>
        <mesh geometry={nodes.Wine_bottle.geometry} material={materials['bottle 1']} position={[-5.74, -1.75, -3.7]} />
      </group>
    </group>
  )
}

useGLTF.preload('/livingroomtedmedia.glb')
