/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations, useMatcapTexture } from '@react-three/drei'
 

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robot6.glb')
  const { actions } = useAnimations(animations, group)

  const [matcapTexture] = useMatcapTexture(1, 1024)
  useEffect(() => { 
    actions.idle.play();
  });
 
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mixamorigHips} />
      <skinnedMesh
        geometry={nodes.Beta_Joints.geometry}
        material={materials.lambert2}
        skeleton={nodes.Beta_Joints.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Beta_Surface.geometry}
        material={matcapTexture}
        skeleton={nodes.Beta_Surface.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/robot6.glb')
