/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sentry.glb')
  const { actions } = useAnimations(animations, group)
 
  useEffect(() => { 
    actions['Take 001'].play();
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0, -1.79]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
              <primitive object={nodes._rootJoint} />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_01_-_Default_0'].geometry}
                material={materials['01_-_Default']}
                skeleton={nodes['G_HeliBlade_01_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_02_-_Default_0'].geometry}
                material={materials['02_-_Default']}
                skeleton={nodes['G_HeliBlade_02_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_03_-_Default_0'].geometry}
                material={materials['03_-_Default']}
                skeleton={nodes['G_HeliBlade_03_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_07_-_Default_0'].geometry}
                material={materials['07_-_Default']}
                skeleton={nodes['G_HeliBlade_07_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_08_-_Default_0'].geometry}
                material={materials['08_-_Default']}
                skeleton={nodes['G_HeliBlade_08_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_09_-_Default_0'].geometry}
                material={materials['09_-_Default']}
                skeleton={nodes['G_HeliBlade_09_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_13_-_Default_0'].geometry}
                material={materials['13_-_Default']}
                skeleton={nodes['G_HeliBlade_13_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes['G_HeliBlade_14_-_Default_0'].geometry}
                material={materials['14_-_Default']}
                skeleton={nodes['G_HeliBlade_14_-_Default_0'].skeleton}
              />
              <skinnedMesh frustumCulled={false}
                geometry={nodes.G_HeliBlade_Mat_ModMat_0.geometry}
                material={materials.Mat_ModMat}
                skeleton={nodes.G_HeliBlade_Mat_ModMat_0.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sentry.glb')
