/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF   } from '@react-three/drei'

export default function Model(props) {

 
  const group = useRef()
  const { nodes, materials } = useGLTF('/tedmedialogotedb.glb')
  return (
    <group name="Tedmedialogo" ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={[200, 200, 200]}>
        <group position={[0, 0, 0]} scale={[200, 200, 200]}>
          <mesh castShadow receiveShadow 
            geometry={nodes.Curve027.geometry}
            material={nodes.Curve027.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve026.geometry}
            material={materials['SVGMat.027']}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve025.geometry}
            material={nodes.Curve025.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh castShadow receiveShadow
            geometry={nodes.Curve024.geometry}
            material={nodes.Curve024.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve023.geometry}
            material={nodes.Curve023.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve022.geometry}
            material={nodes.Curve022.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve021.geometry}
            material={nodes.Curve021.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve020.geometry}
            material={nodes.Curve020.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve019.geometry}
            material={nodes.Curve019.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve018.geometry}
            material={nodes.Curve018.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve017.geometry}
            material={nodes.Curve017.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve016.geometry}
            material={nodes.Curve016.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve015.geometry}
            material={nodes.Curve015.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve014.geometry}
            material={nodes.Curve014.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve013.geometry}
            material={nodes.Curve013.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve012.geometry}
            material={nodes.Curve012.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve011.geometry}
            material={nodes.Curve011.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve010.geometry}
            material={nodes.Curve010.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve009.geometry}
            material={nodes.Curve009.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve008.geometry}
            material={nodes.Curve008.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve007.geometry}
            material={nodes.Curve007.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve006.geometry}
            material={nodes.Curve006.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve005.geometry}
            material={nodes.Curve005.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve004.geometry}
            material={nodes.Curve004.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve003.geometry}
            material={nodes.Curve003.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve001.geometry}
            material={nodes.Curve001.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve.geometry}
            material={nodes.Curve.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
          <mesh  castShadow receiveShadow
            geometry={nodes.Curve002.geometry}
            material={nodes.Curve002.material}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.42, 1.42, 1.42]}
          />
        </group>
      </group> 
    </group>
  )
}

useGLTF.preload('/tedmedialogotedb.glb')
