/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF('/tedmedlogo.glb')
 
   
  const mymaterial =  new THREE.MeshStandardMaterial( {  
    metalness: 1,
    roughness: 0,
    shininess  :  10            
    ,color: 0x0000ff
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[20000, 20000, 20000]}>
        <group position={[0, 0, 0]} scale={[200, 200, 200]}>
          <mesh geometry={nodes.Curve007.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve008.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve009.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve010.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve011.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve012.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve013.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve014.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve015.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve016.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve017.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve018.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve019.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve020.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve021.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve022.geometry} material={nodes.Curve022.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve023.geometry} material={nodes.Curve023.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve024.geometry} material={nodes.Curve024.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve025.geometry} material={nodes.Curve025.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve026.geometry} material={materials['SVGMat.027']} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.Curve027.geometry} material={nodes.Curve027.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterD.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterD1.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterE1.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterF1.geometry} material={mymaterial} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterO.geometry} material={nodes.LetterO.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterR.geometry} material={nodes.LetterR.material} scale={[1.42, 1.42, 1.42]} />
          <mesh geometry={nodes.LetterT.geometry} material={nodes.LetterT.material} scale={[1.42, 1.42, 1.42]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tedmedlogo.glb')
